### ISSUE TITLE
& and | in the pattern of matchwith don't work properly.

### ISSUE THREAD

**Issue by Keiku** [TobCap/matchwith#1]
I expect to get "1-10" as the result of ex(5), but ex function return "other". Why is this?

``` r
> ex <- function(x) 
+   match_with(x
+              , 1 <= x & x <= 10 -> "1-10"
+              , 11 <= x  -> "11+"
+              , . -> "other"
+   )
> ex(5)
[1] "other"
> ex(15)
[1] "11+"
> ex(-1)
[1] "other"
```

**Comment by TobCap** [comment]
Thank you for your reporting, @Keiku.
In the current version of `match_with`, `pattern_i` is regarded as guard clauses when the top node of `pattern_i` matches with one of getGroupMembers("Compare") (i.e. ==, !=, >, <, >=, <=), any(), all(), or `is.` functions. Because `res_i` is evaluated if and only if the result of evaluation of `pattern_i` equals TRUE (which is checked by `isTRUE()`), `all()` or `any()` is required when using `&` or `|` just like the below code. 

``` r
 ex <- function(x) 
  match_with(x
  , all(1 <= x & x <= 10) -> "1-10"
  , all(11 <= x)  -> "11+"
  , . -> "other"
  )
```

I'm gonna revise documents and modify code.
Thanks.
